### ISSUE TITLE
Direct url to Kafka instance is redirecting to 404 page

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-operator#186]
https://cloud.redhat.com/beta/application-services/openshift-streams/kafkas/1rQaeDoM5vhO4vRJ5Z5o8dUD3do

```
 metadata:
    cloudUI: >-
      https://cloud.redhat.com/beta/application-services/openshift-streams/kafkas/1rQaeDoM5vhO4vRJ5Z5o8dUD3do
    provider: rhoas
    saslMechanism: PLAIN
    securityProtocol: SASL_SSL
    type: kafka
```
