### ISSUE TITLE
Create example resource quota objects for operator 

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-operator#195]
https://kubernetes.io/docs/concepts/policy/resource-quotas/#object-count-quota

**Comment by wtrocki** [comment]
Technically something like this would work 

```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: core-object-counts
spec:
  hard:
    count/cloudservicesrequests.rhoas.redhat.com: "1" 
    count/kafkaconnections.rhoas.redhat.com: "1" 
    count/cloudserviceaccountrequest.rhoas.redhat.com: "1" 
```
